### PR TITLE
Update root_ancestor_id of descendants when parent is made a root

### PR DESCRIPTION
**Pull request by shirish-pampoorickal**
Issue: When changing a child node with descendants to a root, the root_ancestor_id for all the descendants would be set to nil.

@naiyt @urnf Appreciate a look

### CODE REVIEW

**Comment by naiyt** [comment]
I'm sure this is fine, but at first glance it looks like in that scenario it would set each descendants `root_ancestor_id` to its own id, not the actual root. Would you be able to explain to me how this works? (Just for my benefit, I'm sure I'm just misunderstanding it.)

**Comment by urnf** [comment]
It's implied that if `root_ancestor_id` does not exist, then the parent _is_ the root, I think?

**Comment by shirish-pampoorickal** [comment]
Yes, exactly what Kevin said. The method is updating the materialized_path & root_ancestor_id of it's descendants in an `after_update`. So, if the `root_ancestor_id` of the story is nil then the it becomes the `root_ancestor` for its children

**Comment by naiyt** [comment]
Alright, cool, LGTM then!

**Comment by shirish-pampoorickal** [comment]
Thanks @naiyt & @urnf!

**Pull request merged**
